### ISSUE TITLE
Level Up

### ISSUE THREAD

**Issue by m-avagyan** [m-avagyan/ublob#19]
## TODOS

- [ ] Browser mock implementation for tests
- [ ] One hundred percent test coverage
- [ ] Automatically bump version
- [ ] Automatically publishing to GitHub and NPM
