### ISSUE TITLE
Next

### ISSUE THREAD

**Issue by m-avagyan** [m-avagyan/ublob#5]
## TODOS

- [x] convert project to es6 module
- [x] convert project to TypeScript
- [ ] connect to GitHub actions
- [ ] write a unit tests
